package com.example.vnkapp.enums.common;

public enum NotificationType {
    ORDER_PLACED, ORDER_CONFIRMED, ORDER_SHIPPED, ORDER_DELIVERED, ORDER_CANCELLED,
    PAYMENT_SUCCESS, PAYMENT_FAILED, REFUND_INITIATED, REFUND_COMPLETED,
    MEDICATION_REMINDER, MEDICATION_REFILL,
    REFERRAL_SIGNUP, REFERRAL_REWARD,
    PROMO, OFFER, GENERAL,
    ACCOUNT_UPDATE, PASSWORD_CHANGED
}
