package com.example.vnkapp.enums.medication;

public enum Frequency {
    ONCE_DAILY, TWICE_DAILY, THRICE_DAILY, FOUR_TIMES_DAILY,
    EVERY_HOUR, EVERY_TWO_HOURS, EVERY_FOUR_HOURS, EVERY_SIX_HOURS, EVERY_EIGHT_HOURS,
    WEEKLY, ALTERNATE_DAYS, AS_NEEDED, CUSTOM
}
